---
language: ruby
cache: bundler

rvm:
- 2.5.3

services:
- mysql
- postgresql

env:
- DB=mysql2
- DB=pg
- DB=sqlite3

gemfile:
- gemfiles/gemfile_50.gemfile
- gemfiles/gemfile_51.gemfile
- gemfiles/gemfile_52.gemfile
- gemfiles/gemfile_60.gemfile

before_install:
- mysql -e 'create database IF NOT EXISTS hash_options_test;'
- psql -c 'create database hash_options_test;' -U postgres
